### ISSUE TITLE
[v0.11.0] -Werror breaks tests build on IA32 (i386 or 32-bit x86)

### ISSUE THREAD

**Issue by jbeich** [AOMediaCodec/libavif#1165]
Regressed by bf4f1a5006fd

```
$ cc --version
FreeBSD clang version 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a303)
Target: i386-unknown-freebsd13.1
Thread model: posix
InstalledDir: /usr/bin
```
```
$ cmake -DAVIF_BUILD_TESTS=on -B /tmp/libavif_build -G Ninja
$ cmake --build /tmp/libavif_build
[...]
tests/gtest/avifincrtest_helpers.cc:136:28: error: implicit conversion loses integer precision: 'unsigned long long' to 'size_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
    size = data->full_size - offset;
         ~ ~~~~~~~~~~~~~~~~^~~~~~~~
1 error generated.
```

**Comment by jbeich** [comment]
`size_t` is `uint32_t` on all 32-bit archs, so it's not just IA32. I've adjusted the summary/subject.

**Comment by wantehchang** [comment]
Jan: Thank you very much for the bug report. Could you please test https://github.com/AOMediaCodec/libavif/pull/1167?

**Comment by jbeich** [comment]
I confirm, after applying #1167 tests built fine and `100% tests passed, 0 tests failed out of 11`. Tested on FreeBSD 12.3 i386 (inside jail on 14.0 amd64).
