### ISSUE TITLE
gdk-pixbuf fails to build with Clang due to -Werror

### ISSUE THREAD

**Issue by jbeich** [AOMediaCodec/libavif#251]
Regressed by #246. From [error log](https://github.com/AOMediaCodec/libavif/files/5031507/libavif-0.8.1_1.log):
```c
contrib/gdk-pixbuf/loader.c:315:29: error: cast from 'const unsigned char *' to 'unsigned char *' drops const qualifier [-Werror,-Wcast-qual]
    rgb.pixels = (uint8_t*) gdk_pixbuf_read_pixels(pixbuf);
                            ^
```

**Comment by novomesk** [comment]
Unfortunately, I'm not using Clang so I can't test.
Can you try if adding `-Wno-cast-qual` option helps?

**Comment by AngryPenguinPL** [comment]
I have the same problem on OpenMandriva Cooker with the Clang 11 compiler.

I can confirm that your pull request #270 has resolved the problem.

Thanks.

**Comment by novomesk** [comment]
Thanks for testing. Now I can use Clang too and I will use it for future commits. I plan more improvements for this component in the future.
But I don't have all Clang versions and new versions sometimes introduce new warnings.

**Comment by jbeich** [comment]
Also works for me. I've field https://github.com/AOMediaCodec/libavif/pull/296 to avoid similar issues in future.

**Comment by novomesk** [comment]
@jbeich If you have some time, can you test the latest git master, as there was [new commit](https://github.com/AOMediaCodec/libavif/commit/82125319d2092c9726b10b5e56bebde37a437dc2) in the gdk-pixbuf loader?

**Comment by jbeich** [comment]
@novomesk, 82125319d209 applied to 0.8.1 still builds fine with Clang 8 (FreeBD 11.3 i386, 12.1 amd64), Clang 11 (FreeBSD 13.0 amd64) and GCC 11. I've tested runtime in [mcomix3](https://github.com/multiSnow/mcomix3) where image rotation works fine before and after.

**Comment by novomesk** [comment]
Thank you!
