### ISSUE TITLE
[0.9.1] AVIF_BUILD_APPS fails to build: undefined reference to `avifDiagnosticsClearError`

### ISSUE THREAD

**Issue by jbeich** [AOMediaCodec/libavif#629]
Regressed by f42d880e3d665fe. From [error log](https://github.com/AOMediaCodec/libavif/files/6512308/libavif-0.9.1.log):
```
$ cmake -DAVIF_CODEC_AOM=ON -DAVIF_CODEC_DAV1D=ON -DAVIF_BUILD_APPS=ON -G Ninja -B /tmp/libavif_build
$ cmake --build /tmp/libavif_build
[...]
FAILED: avifenc
: && /usr/bin/cc   CMakeFiles/avifenc.dir/apps/avifenc.c.o CMakeFiles/avifenc.dir/apps/shared/avifjpeg.c.o CMakeFiles/avifenc.dir/apps/shared/iccjpeg.c.o CMakeFiles/avifenc.dir/apps/shared/avifpng.c.o CMakeFiles/avifenc.dir/apps/shared/avifutil.c.o CMakeFiles/avifenc.dir/apps/shared/y4m.c.o -o avifenc  -Wl,-rpath,/tmp/libavif_build:/usr/local/lib:  libavif.so.11.0.0  -lm  /usr/local/lib/libpng.so  /usr/lib/libz.so  /usr/local/lib/libjpeg.so  -pthread && :
ld: error: undefined symbol: avifDiagnosticsClearError
>>> referenced by avifenc.c
>>>               CMakeFiles/avifenc.dir/apps/avifenc.c.o:(main)
>>> referenced by avifenc.c
>>>               CMakeFiles/avifenc.dir/apps/avifenc.c.o:(convertCropToClap)
>>> referenced by avifutil.c
>>>               CMakeFiles/avifenc.dir/apps/shared/avifutil.c.o:(avifImageDumpInternal)

ld: error: undefined symbol: avifCropRectConvertCleanApertureBox
>>> referenced by avifenc.c
>>>               CMakeFiles/avifenc.dir/apps/avifenc.c.o:(main)
>>> referenced by avifutil.c
>>>               CMakeFiles/avifenc.dir/apps/shared/avifutil.c.o:(avifImageDumpInternal)

ld: error: undefined symbol: avifCleanApertureBoxConvertCropRect
>>> referenced by avifenc.c
>>>               CMakeFiles/avifenc.dir/apps/avifenc.c.o:(convertCropToClap)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
[32/32] Linking C executable avifdec
FAILED: avifdec
: && /usr/bin/cc   CMakeFiles/avifdec.dir/apps/avifdec.c.o CMakeFiles/avifdec.dir/apps/shared/avifjpeg.c.o CMakeFiles/avifdec.dir/apps/shared/iccjpeg.c.o CMakeFiles/avifdec.dir/apps/shared/avifpng.c.o CMakeFiles/avifdec.dir/apps/shared/avifutil.c.o CMakeFiles/avifdec.dir/apps/shared/y4m.c.o -o avifdec  -Wl,-rpath,/tmp/libavif_build:/usr/local/lib:  libavif.so.11.0.0  -lm  /usr/local/lib/libpng.so  /usr/lib/libz.so  /usr/local/lib/libjpeg.so  -pthread && :
ld: error: undefined symbol: avifDiagnosticsClearError
>>> referenced by avifutil.c
>>>               CMakeFiles/avifdec.dir/apps/shared/avifutil.c.o:(avifImageDumpInternal)

ld: error: undefined symbol: avifCropRectConvertCleanApertureBox
>>> referenced by avifutil.c
>>>               CMakeFiles/avifdec.dir/apps/shared/avifutil.c.o:(avifImageDumpInternal)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by joedrago** [comment]
This sounds more like you are not building the new file `diag.c`. Can you try building in a fresh build directory?

**Comment by joedrago** [comment]
Oh! I think I see what is going on. `avifDiagnosticsClearError()` might need to be exported here. I'm not sure how our CI didn't catch this. Verifying now.

**Comment by joedrago** [comment]
Can you try this patch and let me know if it resolves this for you?

```
diff --git a/include/avif/avif.h b/include/avif/avif.h
index f83ef7c..df4dd5c 100644
--- a/include/avif/avif.h
+++ b/include/avif/avif.h
@@ -304,7 +304,7 @@ typedef struct avifDiagnostics
     char error[AVIF_DIAGNOSTICS_ERROR_BUFFER_SIZE];
 } avifDiagnostics;
 
-void avifDiagnosticsClearError(avifDiagnostics * diag);
+AVIF_API void avifDiagnosticsClearError(avifDiagnostics * diag);
 
 // ---------------------------------------------------------------------------
 // Optional transformation structs
```

**Comment by jbeich** [comment]
Still fails:
```
$ cmake --build /tmp/libavif_build
[29/30] Linking C executable avifdec
FAILED: avifdec
: && /usr/bin/cc   CMakeFiles/avifdec.dir/apps/avifdec.c.o CMakeFiles/avifdec.dir/apps/shared/avifjpeg.c.o CMakeFiles/avifdec.dir/apps/shared/iccjpeg.c.o CMakeFiles/avifdec.dir/apps/shared/avifpng.c.o CMakeFiles/avifdec.dir/apps/shared/avifutil.c.o CMakeFiles/avifdec.dir/apps/shared/y4m.c.o -o avifdec  -Wl,-rpath,/tmp/libavif_build:/usr/local/lib:  libavif.so.11.0.0  -lm  /usr/local/lib/libpng.so  /usr/lib/libz.so  /usr/local/lib/libjpeg.so  -pthread && :
ld: error: undefined symbol: avifCropRectConvertCleanApertureBox
>>> referenced by avifutil.c
>>>               CMakeFiles/avifdec.dir/apps/shared/avifutil.c.o:(avifImageDumpInternal)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
[30/30] Linking C executable avifenc
FAILED: avifenc
: && /usr/bin/cc   CMakeFiles/avifenc.dir/apps/avifenc.c.o CMakeFiles/avifenc.dir/apps/shared/avifjpeg.c.o CMakeFiles/avifenc.dir/apps/shared/iccjpeg.c.o CMakeFiles/avifenc.dir/apps/shared/avifpng.c.o CMakeFiles/avifenc.dir/apps/shared/avifutil.c.o CMakeFiles/avifenc.dir/apps/shared/y4m.c.o -o avifenc  -Wl,-rpath,/tmp/libavif_build:/usr/local/lib:  libavif.so.11.0.0  -lm  /usr/local/lib/libpng.so  /usr/lib/libz.so  /usr/local/lib/libjpeg.so  -pthread && :
ld: error: undefined symbol: avifCropRectConvertCleanApertureBox
>>> referenced by avifenc.c
>>>               CMakeFiles/avifenc.dir/apps/avifenc.c.o:(main)
>>> referenced by avifutil.c
>>>               CMakeFiles/avifenc.dir/apps/shared/avifutil.c.o:(avifImageDumpInternal)

ld: error: undefined symbol: avifCleanApertureBoxConvertCropRect
>>> referenced by avifenc.c
>>>               CMakeFiles/avifenc.dir/apps/avifenc.c.o:(convertCropToClap)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by joedrago** [comment]
Yeah, the new avifCropRect code was susceptible to the same issue. I've fixed all three, pushed the commit, and moved the published tag. We use AppVeyor, Travis, and Github Actions for our CI, but only the Travis CI would have caught this particular (shared lib) flavor of issue, and it has been down for a few weeks due to some issue with "OSS Credits". Sorry for the swirl.
