### ISSUE TITLE
Fails to build with Clang 10

### ISSUE THREAD

**Issue by jbeich** [AOMediaCodec/libavif#106]
Regressed by e2c3c87c7dc7.
```c
$ CC=clang10 CXX=clang++10 cmake -GNinja -DAVIF_CODEC_AOM=on -DAVIF_BUILD_APPS=on .
$ ninja
[...]
src/alpha.c:169:44: error: implicit conversion from 'int' to 'float' may lose precision [-Werror,-Wimplicit-int-float-conversion]
                            float alphaF = srcAlpha / srcMaxChannelF;
                                           ^~~~~~~~ ~
src/alpha.c:183:44: error: implicit conversion from 'int' to 'float' may lose precision [-Werror,-Wimplicit-int-float-conversion]
                            float alphaF = srcAlpha / srcMaxChannelF;
                                           ^~~~~~~~ ~
src/alpha.c:198:40: error: implicit conversion from 'int' to 'float' may lose precision [-Werror,-Wimplicit-int-float-conversion]
                        float alphaF = srcAlpha / srcMaxChannelF;
                                       ^~~~~~~~ ~
src/alpha.c:221:44: error: implicit conversion from 'int' to 'float' may lose precision [-Werror,-Wimplicit-int-float-conversion]
                            float alphaF = srcAlpha / srcMaxChannelF;
                                           ^~~~~~~~ ~
src/alpha.c:236:44: error: implicit conversion from 'int' to 'float' may lose precision [-Werror,-Wimplicit-int-float-conversion]
                            float alphaF = srcAlpha / srcMaxChannelF;
                                           ^~~~~~~~ ~
src/alpha.c:252:40: error: implicit conversion from 'int' to 'float' may lose precision [-Werror,-Wimplicit-int-float-conversion]
                        float alphaF = srcAlpha / srcMaxChannelF;
                                       ^~~~~~~~ ~
src/alpha.c:274:44: error: implicit conversion from 'int' to 'float' may lose precision [-Werror,-Wimplicit-int-float-conversion]
                            float alphaF = srcAlpha / srcMaxChannelF;
                                           ^~~~~~~~ ~
src/alpha.c:289:44: error: implicit conversion from 'int' to 'float' may lose precision [-Werror,-Wimplicit-int-float-conversion]
                            float alphaF = srcAlpha / srcMaxChannelF;
                                           ^~~~~~~~ ~
src/alpha.c:305:40: error: implicit conversion from 'int' to 'float' may lose precision [-Werror,-Wimplicit-int-float-conversion]
                        float alphaF = srcAlpha / srcMaxChannelF;
                                       ^~~~~~~~ ~
src/alpha.c:329:44: error: implicit conversion from 'int' to 'float' may lose precision [-Werror,-Wimplicit-int-float-conversion]
                            float alphaF = srcAlpha / srcMaxChannelF;
                                           ^~~~~~~~ ~
src/alpha.c:345:44: error: implicit conversion from 'int' to 'float' may lose precision [-Werror,-Wimplicit-int-float-conversion]
                            float alphaF = srcAlpha / srcMaxChannelF;
                                           ^~~~~~~~ ~
src/alpha.c:362:40: error: implicit conversion from 'int' to 'float' may lose precision [-Werror,-Wimplicit-int-float-conversion]
                        float alphaF = srcAlpha / srcMaxChannelF;
                                       ^~~~~~~~ ~
12 errors generated.
```

**Comment by joedrago** [comment]
I should get a CI going with Clang 10.
