### ISSUE TITLE
AVIF_BUILD_APPS fails to build on 32-bit architectures due to -Werror

### ISSUE THREAD

**Issue by jbeich** [AOMediaCodec/libavif#126]
Regressed by 21bc4dfbe5ba. See error logs: [i386](https://github.com/AOMediaCodec/libavif/files/4490897/libavif-0.7.1.log), [armv7](https://github.com/AOMediaCodec/libavif/files/4490895/libavif-0.7.1.log).

```c
apps/avifdump.c:66:24: error: format specifies type 'size_t' (aka 'unsigned int') but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
                       decoder->timescale,
                       ^~~~~~~~~~~~~~~~~~
apps/avifdump.c:68:24: error: format specifies type 'size_t' (aka 'unsigned int') but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
                       decoder->durationInTimescales,
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
apps/avifdump.c:77:20: error: format specifies type 'size_t' (aka 'unsigned int') but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
                   decoder->imageTiming.ptsInTimescales,
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
apps/avifdump.c:79:20: error: format specifies type 'size_t' (aka 'unsigned int') but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
                   decoder->imageTiming.durationInTimescales);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by joedrago** [comment]
Shoot, good catch. I need to add a 32bit build to my CIs.

I've fixed it here:

https://github.com/AOMediaCodec/libavif/commit/22c57ea6176d3abab48e2b0db87eeb5552eb2833
